### ISSUE TITLE
skipping shacl generation

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/sheets_and_friends#11]
was there an error? what was it?

**Comment by turbomam** [comment]
> INFO:root: ARGS: {'mergeimports': True}
INFO:root:  WRITING TO: project/shex/soil_emls_jgi_mg_new_shuttled_modified.shex
INFO:root:Generating: shacl
INFO:root: SCHEMA: artifacts/soil_emls_jgi_mg_new_shuttled_modified.yaml
INFO:root: PARENT=project/shacl
INFO:root: ARGS: {'mergeimports': True}
INFO:root:Loading schema https://w3id.org/linkml/types from artifacts/soil_emls_jgi_mg_new_shuttled_modified.yaml
Traceback (most recent call last):
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/sheets-and-friends-XU_YBljG-py3.9/bin/gen-project", line 8, in <module>
    sys.exit(cli())
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/sheets-and-friends-XU_YBljG-py3.9/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/sheets-and-friends-XU_YBljG-py3.9/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/sheets-and-friends-XU_YBljG-py3.9/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/sheets-and-friends-XU_YBljG-py3.9/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/sheets-and-friends-XU_YBljG-py3.9/lib/python3.9/site-packages/linkml/generators/projectgen.py", line 191, in cli
    gen.generate(yamlfile, project_config)
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/sheets-and-friends-XU_YBljG-py3.9/lib/python3.9/site-packages/linkml/generators/projectgen.py", line 114, in generate
    gen_dump = gen.serialize(**serialize_args)
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/sheets-and-friends-XU_YBljG-py3.9/lib/python3.9/site-packages/linkml/generators/shaclgen.py", line 40, in serialize
    g = self.as_graph()
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/sheets-and-friends-XU_YBljG-py3.9/lib/python3.9/site-packages/linkml/generators/shaclgen.py", line 71, in as_graph
    slot_uri = URIRef(sv.get_uri(s, expand=True))
  File "/Users/MAM/Library/Caches/pypoetry/virtualenvs/sheets-and-friends-XU_YBljG-py3.9/lib/python3.9/site-packages/linkml_runtime/utils/schemaview.py", line 656, in get_uri
    schema = next(sc for sc in self.schema_map.values() if sc.id == e.from_schema)
StopIteration
